let data = [
    {
        "name": "Gengar - *",
        "pinned": false,
        "icon": "images/mini_icons/gengar.png",
        "sprites": "images/sprites/gengar.png",
        "gifs": "images/gifs/gengar.gif",
        "iniciative": "4",
        "movement": "5 (+1)",
        "attack": "8",
        "defense": "5 (+1)"
    },
    {
        "name": "Arcanine - *",
        "pinned": false,
        "icon": "images/mini_icons/arcanine.png",
        "sprites": "images/sprites/arcanine.png",
        "gifs": "images/gifs/arcanine.gif",
        "iniciative": "1",
        "movement": "2 (+2)",
        "attack": "7",
        "defense": "8"
    },
    {
        "name": "Cinderace - *",
        "pinned": false,
        "icon": "images/mini_icons/cinderace.png",
        "sprites": "images/sprites/cinderace.png",
        "gifs": "images/gifs/cinderace.gif",
        "iniciative": "8",
        "movement": "7 (+1)",
        "attack": "4 (+4)",
        "defense": "1 (+3)"
    },
    {
        "name": "Metagross - *",
        "pinned": false,
        "icon": "images/mini_icons/metagross.png",
        "sprites": "images/sprites/metagross.png",
        "gifs": "images/gifs/metagross.gif",
        "iniciative": "6",
        "movement": "5",
        "attack": "5",
        "defense": "4 (+1)"
    },
    {
        "name": "Misdreavus - *",
        "pinned": false,
        "icon": "images/mini_icons/misdreavus.png",
        "sprites": "images/sprites/misdreavus.png",
        "gifs": "images/gifs/misdreavus.gif",
        "iniciative": "5",
        "movement": "5 (+1)",
        "attack": "1 (+7)",
        "defense": "3"
    },
    {
        "name": "Snorlax - *",
        "pinned": false,
        "icon": "images/mini_icons/snorlax.png",
        "sprites": "images/sprites/snorlax.png",
        "gifs": "images/gifs/snorlax.gif",
        "iniciative": "3",
        "movement": "6",
        "attack": "5 (+3)",
        "defense": "6"
    },
    {
        "name": "Absol - *",
        "pinned": false,
        "icon": "images/mini_icons/absol.png",
        "sprites": "images/sprites/absol.png",
        "gifs": "images/gifs/absol.gif",
        "iniciative": "7",
        "movement": "5",
        "attack": "3",
        "defense": "2 (+3)"
    },
    {
        "name": "Tinkaton - **",
        "pinned": false,
        "icon": "images/mini_icons/tinkaton.png",
        "sprites": "images/sprites/tinkaton.png",
        "gifs": "images/gifs/tinkaton.gif",
        "iniciative": "4",
        "movement": "3 (+2)",
        "attack": "8",
        "defense": "7"
    },
    {
        "name": "Wobbuffet - **",
        "pinned": false,
        "icon": "images/mini_icons/wobbuffet.png",
        "sprites": "images/sprites/wobbuffet.png",
        "gifs": "images/gifs/wobbuffet.gif",
        "iniciative": "3",
        "movement": "5 (+1)",
        "attack": "8",
        "defense": "7"
    },
    {
        "name": "Sceptile - **",
        "pinned": false,
        "icon": "images/mini_icons/sceptile.png",
        "sprites": "images/sprites/sceptile.png",
        "gifs": "images/gifs/sceptile.gif",
        "iniciative": "4",
        "movement": "5 (+1)",
        "attack": "5",
        "defense": "4 (+2)"
    },
    {
        "name": "Totodile - **",
        "pinned": false,
        "icon": "images/mini_icons/totodile.png",
        "sprites": "images/sprites/totodile.png",
        "gifs": "images/gifs/totodile.gif",
        "iniciative": "7",
        "movement": "3 (+2)",
        "attack": "7",
        "defense": "4"
    },
    {
        "name": "Lugia - **",
        "pinned": false,
        "icon": "images/mini_icons/lugia.png",
        "sprites": "images/sprites/lugia.png",
        "gifs": "images/gifs/lugia.gif",
        "iniciative": "7",
        "movement": "1 (+7)",
        "attack": "6",
        "defense": "5"
    },
    {
        "name": "Palafin - **",
        "pinned": false,
        "icon": "images/mini_icons/palafin.png",
        "sprites": "images/sprites/palafin.png",
        "gifs": "images/gifs/palafin.gif",
        "iniciative": "5",
        "movement": "1 (+4)",
        "attack": "6",
        "defense": "6"
    },
    {
        "name": "Galvantula - **",
        "pinned": false,
        "icon": "images/mini_icons/galvantula.png",
        "sprites": "images/sprites/galvantula.png",
        "gifs": "images/gifs/galvantula.gif",
        "iniciative": "7",
        "movement": "6 (+1)",
        "attack": "2",
        "defense": "1"
    },
    {
        "name": "Flygon - **",
        "pinned": false,
        "icon": "images/mini_icons/flygon.png",
        "sprites": "images/sprites/flygon.png",
        "gifs": "images/gifs/flygon.gif",
        "iniciative": "8",
        "movement": "6",
        "attack": "4 (+4)",
        "defense": "3 (+5)"
    },
    {
        "name": "Tyranitar - ***",
        "pinned": false,
        "icon": "images/mini_icons/tyranitar.png",
        "sprites": "images/sprites/tyranitar.png",
        "gifs": "images/gifs/tyranitar.gif",
        "iniciative": "1",
        "movement": "2 (+2)",
        "attack": "8",
        "defense": "8"
    },
    {
        "name": "Charizard - ***",
        "pinned": false,
        "icon": "images/mini_icons/charizard.png",
        "sprites": "images/sprites/charizard.png",
        "gifs": "images/gifs/charizard.gif",
        "iniciative": "6",
        "movement": "4 (+4)",
        "attack": "4 (+4)",
        "defense": "4"
    },
    {
        "name": "Tatsugiri - ***",
        "pinned": false,
        "icon": "images/mini_icons/tatsugiri.png",
        "sprites": "images/sprites/tatsugiri.png",
        "gifs": "images/gifs/tatsugiri.gif",
        "iniciative": "6",
        "movement": "7 (+1)",
        "attack": "3 (+2)",
        "defense": "2 (+2)"
    },
    {
        "name": "Eevee - ***",
        "pinned": false,
        "icon": "images/mini_icons/eevee.png",
        "sprites": "images/sprites/eevee.png",
        "gifs": "images/gifs/eevee.gif",
        "iniciative": "5 (+3)",
        "movement": "5",
        "attack": "4 (+2)",
        "defense": "4"
    },
    {
        "name": "Pikachu - ***",
        "pinned": false,
        "icon": "images/mini_icons/pikachu.png",
        "sprites": "images/sprites/pikachu.png",
        "gifs": "images/gifs/pikachu.gif",
        "iniciative": "4",
        "movement": "7",
        "attack": "5",
        "defense": "2"
    },
    {
        "name": "Torterra - ***",
        "pinned": false,
        "icon": "images/mini_icons/torterra.png",
        "sprites": "images/sprites/torterra.png",
        "gifs": "images/gifs/torterra.gif",
        "iniciative": "1",
        "movement": "3 (+1)",
        "attack": "5",
        "defense": "8"
    },
    {
        "name": "Whimsicott - ***",
        "pinned": false,
        "icon": "images/mini_icons/whimsicott.png",
        "sprites": "images/sprites/whimsicott.png",
        "gifs": "images/gifs/whimsicott.gif",
        "iniciative": "8",
        "movement": "7 (+1)",
        "attack": "4",
        "defense": "1"
    },
    {
        "name": "Quaquaval - ***",
        "pinned": false,
        "icon": "images/mini_icons/quaquaval.png",
        "sprites": "images/sprites/quaquaval.png",
        "gifs": "images/gifs/quaquaval.gif",
        "iniciative": "7",
        "movement": "5 (+1)",
        "attack": "4 (+4)",
        "defense": "4"
    },
    {
        "name": "Falinks - ***",
        "pinned": false,
        "icon": "images/mini_icons/falinks.png",
        "sprites": "images/sprites/falinks.png",
        "gifs": "images/gifs/falinks.gif",
        "iniciative": "2",
        "movement": "4",
        "attack": "8",
        "defense": "7"
    },
    {
        "name": "Solrock - ***",
        "pinned": false,
        "icon": "images/mini_icons/solrock.png",
        "sprites": "images/sprites/solrock.png",
        "gifs": "images/gifs/solrock.gif",
        "iniciative": "4",
        "movement": "5 (+1)",
        "attack": "5",
        "defense": "4"
    },
    {
        "name": "Rotom\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n - ****",
        "pinned": false,
        "icon": "images/mini_icons/rotom.png",
        "sprites": "images/sprites/rotom.png",
        "gifs": "images/gifs/rotom.gif",
        "iniciative": "2",
        "movement": "4 (+1)",
        "attack": "5 (+1)",
        "defense": "5 (+1)"
    },
    {
        "name": "Squirtle - ****",
        "pinned": false,
        "icon": "images/mini_icons/squirtle.png",
        "sprites": "images/sprites/squirtle.png",
        "gifs": "images/gifs/squirtle.gif",
        "iniciative": "8",
        "movement": "5 (+1)",
        "attack": "3",
        "defense": "1 (+3)"
    },
    {
        "name": "Ditto - ****",
        "pinned": false,
        "icon": "images/mini_icons/ditto.png",
        "sprites": "images/sprites/ditto.png",
        "gifs": "images/gifs/ditto.gif",
        "iniciative": "3",
        "movement": "1 (+3)",
        "attack": "5 (+1)",
        "defense": "3 (+2)"
    },
    {
        "name": "Chandelure - ****",
        "pinned": false,
        "icon": "images/mini_icons/chandelure.png",
        "sprites": "images/sprites/chandelure.png",
        "gifs": "images/gifs/chandelure.gif",
        "iniciative": "1",
        "movement": "2 (+3)",
        "attack": "2 (+1)",
        "defense": "5 (+1)"
    },
    {
        "name": "Vulpix - ****",
        "pinned": false,
        "icon": "images/mini_icons/vulpix.png",
        "sprites": "images/sprites/vulpix.png",
        "gifs": "images/gifs/vulpix.gif",
        "iniciative": "2",
        "movement": "4 (+1)",
        "attack": "5",
        "defense": "6"
    },
    {
        "name": "Heracross - ****",
        "pinned": false,
        "icon": "images/mini_icons/heracross.png",
        "sprites": "images/sprites/heracross.png",
        "gifs": "images/gifs/heracross.gif",
        "iniciative": "3 (+2)",
        "movement": "1 (+3)",
        "attack": "5 (+2)",
        "defense": "4 (+3)"
    },
    {
        "name": "Spoink - ****",
        "pinned": false,
        "icon": "images/mini_icons/spoink.png",
        "sprites": "images/sprites/spoink.png",
        "gifs": "images/gifs/spoink.gif",
        "iniciative": "1",
        "movement": "2 (+2)",
        "attack": "5 (+3)",
        "defense": "6"
    }
];
export default data;